# Generated by Django 4.2.7 on 2024-03-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='ca',
        ),
    ]
