# Generated by Django 4.2.7 on 2024-03-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_image_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='ca',
            new_name='tree_name',
        ),
    ]
